### ISSUE TITLE
Retention period doesn't work

### ISSUE THREAD

**Issue by upcFrost** [exoscale-labs/snap-o-matic#2]
Hi,

I have noticed that the retention period and automatic snapshot deletion stopped working some time ago (approximately in the beginning of May).
In the dry run mode I can see snapshot being created but nothing about deleting other snapshots.

Might it be that the API has changed?

Best regards,
Petr

**Comment by upcFrost** [comment]
Update: I think the issue is here
```go
if !isAutosnapshot(snapshot) || strings.ToLower(snapshot.State) != "backedup" {
    continue
}
```

All my snapshots have their state as `Exported`, not `BackedUp`

**Comment by arnaudgeiser** [comment]
The mentioned bug doesn't exist anymore.
Sorry for the delay.

**Comment by m-kuhn** [comment]
Could this be closed then?
